name: plant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/plants.png
    - assets/branch.png
    - assets/plants/plants_0.png
    - assets/plants/plants_1.png
    - assets/plants/plants_2.png
    - assets/plants/plants_3.png
    - assets/plants/plants_4.png
    - assets/plants/plants_5.png
    - assets/plants/plants_6.png
    - assets/plants/plants_7.png
    - assets/plants/plants_8.png
